### ISSUE TITLE
Logs not pushed to GrayLog

### ISSUE THREAD

**Issue by shah-keyur** [mattwcole/gelf-extensions-logging#8] opened 2018-05-08 11:27 UTC
Hi ,

Based on the sample example for .NeCore2

I have configure GelfLogger and then injecting the Ilogger<ValueController>
.
Then using the logger.LogInformation("Log in gray log").

But its not appears in the Graylog.

On application start I am logging exactly as the sample example and its logs in gay log but not from controller.

`public void ConfigureServices(IServiceCollection services)
		{
services.Configure<GelfLoggerOptions>(Configuration.GetSection("Graylog"))
				.AddLogging(loggingBuilder => loggingBuilder
					.AddConfiguration(Configuration.GetSection("Logging"))					
					.AddGelf());

using (var serviceProvider = services.BuildServiceProvider())
			{
				UseLogger(serviceProvider.GetRequiredService<ILogger<Program>>());
			}
}`

private static void UseLogger(ILogger<Program> logger)
		{
			const string framework = "netcoreapp-4.0";

			logger.LogInformation("Information log from {framework}", framework);

			using (logger.BeginScope(("scope_field_1", "foo")))
			{
				logger.LogDebug("Debug log from {framework}", framework);

				using (logger.BeginScope(new Dictionary<string, object>
				{
					["scope_field_2"] = "bar",
					["scope_field_3"] = "baz"
				}))
				{
					logger.LogTrace("Trace log from {framework}", framework);
				}

				logger.LogError(new EventId(), new Exception("Example exception!"),
					"Error log from {framework}", framework);
			}
		}

public ValueController( ILogger logger)
		{
			this.logger = llogger;
			
		}
public async Task<IActionResult> GetValues()
		{
			try
			{
				
					logger.Log(LogLevel.Information, "Get all years method is called{framework}", "2.0");
					logger.LogDebug("Get all years method is called{framework}", "2.0");
					logger.LogError("error occured");

			

				
			}
			catch (System.Exception ex)
			{
				// log exceptions
				return StatusCode((int)HttpStatusCode.InternalServerError);
			}
		}

using .net core  2.1 final previews 2

Appreciate your help.

Thanks,
Keyur

**Comment by shah-keyur** [comment] 2018-05-08 11:29
It would be good if you add working example to log from a controller.

Thanks,

**Comment by mattwcole** [comment] 2018-05-08 12:42
You might want to check out the [ASP.NET Core logging documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x&view=aspnetcore-2.1) referenced at the top of the readme; it shows how to use a logger from a controller as well as how to add custom providers like this one. I would follow the steps there and make sure console logging is working from your controller before adding the GELF provider.

The apps in the `/samples` directory are for those building console apps that _are not_ using ASP.NET, but you could still run one and check that it sends logs to your Graylog server.

**Comment by shah-keyur** [comment] 2018-05-08 13:03
Thanks,

Yeah from the sample application it is working.

Need figure it out why not working in the my application.

Thanks,
-Keyur

**Comment by mattwcole** [comment] 2018-05-08 13:12
It sounds like it would help if I added an example ASP.NET app. I'll try to get one up within the next few days. Hopefully you figure out your issue before then!

**Comment by shah-keyur** [comment] 2018-05-08 13:14
I suspect the version the one which is working with a controller is Aspnetcore 2.0 and I am using 2.1 preview final 2

**Comment by mattwcole** [comment] 2018-05-08 14:55
In theory it should still work, I'll have to look into it.

**Comment by mattwcole** [comment] 2018-05-08 21:29
I have added a sample ASP.NET Core 2.0 project [here](https://github.com/mattwcole/gelf-extensions-logging/tree/dev/samples/Gelf.Extensions.Logging.Samples.AspNetCore2) in case that helps.

**Comment by shah-keyur** [comment] 2018-05-09 04:52
Hi MattwCole,

I confirm that its the issue with AspnetCore2.1.

I try to reproduce it with a sample project and it doesn't work. Then I changed the AspnetCore2.0 and it worked.

Thanks,
Keyur

**Comment by mattwcole** [comment] 2018-05-09 07:50
Thanks for confirming this. Now that we know what the problem is, I will close this issue. Support for 2.1 will be tracked in #9.

**Comment by shah-keyur** [comment] 2018-05-09 07:51
Appreciate your help!

**Closed as completed by mattwcole** 2018-05-09 07:50 UTC
